Hw3
ocelot335/tinkBot pull request #3
Opened 2024-03-03 20:12 UTC by ocelot335

В спецификации для delete должно посылаться body, но у delete нет body. Наверное, надо менять спецификацию, даже Swagger ругается на неё. Я не сделал этот метод в клиенте бота

2024-03-03 20:13 UTC, ocelot335 commented
Маленькие моменты по hw2 я исправлю чуть позже

2024-03-09 12:58 UTC, lwbeamer requested changes

2024-03-09 12:58 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/clients/ScrapperClient.java
> +            )
Эти два onStatus кидают один и тот же ScrapperApiException. Можно объединить в один, закинув в первый аргумент (Predicate) функцию с условием типа BAD_REQUEST || NOT_FOUND

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.ResponseSpec.html#onStatus(java.util.function.Predicate,java.util.function.Function)

2024-03-09 12:58 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/clients/ScrapperClient.java
> +            )
Здесь и в остальных местах аналогично

2024-03-09 12:58 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/clients/ScrapperClient.java
> +        // даже Swagger ругается на неё
В целом да, с delete редко посылается тело, но это не панацея, то есть не всегда имеет практический смысл строжайше следовать всем правилам REST. Но даже в официальных доках это не запрещается - https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

> Request has body -> May

Что касается технической возможности это сделать, она существует - https://stackoverflow.com/a/71171894

В нашем случае передавать ссылку в параметрах запроса кажется не очень удобно, поэтому используется тело

2024-03-09 12:58 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/controller/BotController.java
> +@Validated
`@Validated` здесь не нужна.

`@Valid` перед телом запроса достаточно

2024-03-09 12:58 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/clients/BotClient.java
> +    //Тут происходит так, что при подучении статуса ошибки 400 выбрасывается ошибка, правильно ли это??
Да. Когда будем выполнять этот запрос, нужно знать если что-то пошло не так. В будущем возможно пригодится добавить отлов не только 400, но и других кодов

2024-03-09 12:58 UTC, lwbeamer commented on scrapper/src/main/java/edu/java/controller/ScrapperController.java
> +@Validated
Тут `@Validated` тоже не нужна в данном случае

2024-03-09 12:58 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/clients/dto/LinkResponse.java
> +    // пока реализовано криво, бд добавится в следующей итерации
Да, id из БД, в этой дз не пока просто декларируем

2024-03-09 23:39 UTC, ocelot335 commented
@lwbeamer, исправил.

2024-03-17 13:56 UTC, merged