Hw4
ocelot335/tinkBot pull request #4
Opened 2024-03-10 19:38 UTC by ocelot335

2024-03-10 19:50 UTC, ocelot335 commented
Откуда появились проверки и code coverage? Проверка падает от того, что не может подключиться по порту 54320(Я сделал такой потому что у меня с локальным постгресом коллизия)ю

2024-03-17 13:41 UTC, lwbeamer requested changes

2024-03-17 13:41 UTC, lwbeamer commented on migrations/schema.sql
> +    id              bigint generated always as identity,
chat_id (telegramId) уже изначально хорошо подходит на роль promary_key. Суррогатный id здесь избыточен

2024-03-17 13:41 UTC, lwbeamer commented on migrations/schema.sql
> +)
Как будешь узнавать, когда последний раз сходили по ссылке и проверили ее на наличие обновлений? Ссылок может быть очень много и постоянно для каждой ходить в API затратно. Поэтому нужен флаг типа checked_at, который отфильтрует ненужные походы и в будущем можно будет гибко настроить интервалы проверок и что именно считать "устаревшей" ссылкой

2024-03-17 14:02 UTC, lwbeamer commented
> Откуда появились проверки и code coverage? Проверка падает от того, что не может подключиться по порту 54320(Я сделал такой потому что у меня с локальным постгресом коллизия)
> 
> UPD: Здесь ранее была проверка билда тестов, один из которых падал из-за аннотации @ SpringBootTest. Почему то в этом случае Spring хочет подключиться к бд, а докер контейнер в это время(и во время проверки на гитхаб) не запущен

Проверки и coverage тянутся из github workflow. Покрытие собирается jacoco плагином

```
      - id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/scrapper/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 30
          title: Code Coverage
          update-comment: true
```

Насчет падающих тестов. У тебя когда в github CI запускается приложение - падает на том, что не может подключиться к БД по причине ее отсутствия, правильно понимаю? На самом деле сходу сложно сказать причину, возможно обращение идет не по имени контейнера (postgresql), а через localhost, но это догадки. Но сейчас же вроде зеленая галка стоит типа все ок прошло
<img width="248" alt="image" src="https://github.com/ocelot335/tinkBot/assets/73843667/1c45f95c-63a7-44d0-ac24-02912d317e05">
 или я чего-то не понял)

2024-03-17 14:12 UTC, ocelot335 commented on migrations/schema.sql
> +    id              bigint generated always as identity,
Это ок, если я просто schema.sql перепишу, удалив контейнер и volume? Или надо дописывать что-то такое, чтобы liquibase провёл миграции?

```
--changeset ocelot335:4

alter table chats drop constraint chats_pkey;
alter table chats drop column id;

alter table chats add primary key (telegramId);

--rollback alter table chats drop constraint telegramId; alter table chats add column id bigint generated always as identity; alter table chats add primary key (id); alter table chats add unique (telegramId);

--changeset ocelot335:5
alter table subscribes drop constraint subscribes_chatid_fkey;
alter table subscribes add constraint subscribes_chatid_fkey foreign key(chatId) references chats(telegramId) on delete cascade;

--rollback alter table subscribes drop constraint subscribes_chatid_fkey; alter table subscribes add constraint subscribes_chatid_fkey foreign key(chatId) references chats(id) on delete cascade;
```

2024-03-17 14:14 UTC, ocelot335 commented
> > Откуда появились проверки и code coverage? Проверка падает от того, что не может подключиться по порту 54320(Я сделал такой потому что у меня с локальным постгресом коллизия)
> > UPD: Здесь ранее была проверка билда тестов, один из которых падал из-за аннотации @ SpringBootTest. Почему то в этом случае Spring хочет подключиться к бд, а докер контейнер в это время(и во время проверки на гитхаб) не запущен
> 
> Проверки и coverage тянутся из github workflow. Покрытие собирается jacoco плагином
> 
> ```
>       - id: jacoco
>         uses: madrapps/jacoco-report@v1.6.1
>         if: ( github.event_name != 'workflow_dispatch' )
>         with:
>           paths: ${{ github.workspace }}/scrapper/target/site/jacoco/jacoco.xml
>           token: ${{ secrets.GITHUB_TOKEN }}
>           min-coverage-overall: 30
>           min-coverage-changed-files: 30
>           title: Code Coverage
>           update-comment: true
> ```
> 
> Насчет падающих тестов. У тебя когда в github CI запускается приложение - падает на том, что не может подключиться к БД по причине ее отсутствия, правильно понимаю? На самом деле сходу сложно сказать причину, возможно обращение идет не по имени контейнера (postgresql), а через localhost, но это догадки. Но сейчас же вроде зеленая галка стоит типа все ок прошло <img alt="image" width="248" src="https://private-user-images.githubusercontent.com/73843667/313478351-1c45f95c-63a7-44d0-ac24-02912d317e05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODUxMjEsIm5iZiI6MTcxMDY4NDgyMSwicGF0aCI6Ii83Mzg0MzY2Ny8zMTM0NzgzNTEtMWM0NWY5NWMtNjNhNy00NGQwLWFjMjQtMDI5MTJkMzE3ZTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE0MTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYjU3NjZiZWIwNTE3NDEyMjU1MzU3YjhhMmU5OTI0MWI3NDBmMzM0Y2E1MDhlMThmMzk4MGViYjQzNWQxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0XXhVPbUZQxVw_MFjU8bZLnRhFJMCw4a8sPDlH8hCKY"> или я чего-то не понял)

А почему их раньше не было?

2024-03-17 21:33 UTC, lwbeamer commented
>А почему их раньше не было?

сам с ходу не понимаю, попробую выяснить/поспрашивать, но главное что появились сейчас

2024-03-22 08:37 UTC, lwbeamer commented on migrations/schema.sql
> +    id              bigint generated always as identity,
Не обязательно удалять весь контейнер и volume (если ты про БД), в данном случае можно просто удалить из него таблицы вручную и при новом запуске liquibase уже накатит обновленные миграции. В реальной разработке да, обычно пишут доп. миграции на удаление чего-либо, но здесь не нужно точно. Тебе еще скорее всего придется в таблице databasechangelog удалить запись о том, что миграция накатилась для старой версии миграций. Так что нет, дропать с помощью ликвы не нужно как ты описал, можно руками)

P.S. вынеси миграции лучше в три разных файла, описывать changeset'ы в одном файле не очень хорошая практика, потому будет сложно искать и отлаживать, когда файл будет разростататься

2024-03-28 00:57 UTC, ocelot335 commented
@lwbeamer, если что, то замечания отсюда исправлены в hw5

2024-03-29 18:23 UTC, lwbeamer commented
> @lwbeamer, если что, то замечания отсюда исправлены в hw5

@ocelot335 Там как вижу все еще остался суррогатный id у chats и все changeSet'ы все еще в одном файле(

<img width="673" alt="image" src="https://github.com/ocelot335/tinkBot/assets/73843667/901468bf-c648-4d73-a6eb-b2b6e229ca79">

2024-03-29 18:29 UTC, lwbeamer commented
И на платформе тоже меняй статус на повторную проверку когда фиксанул

2024-04-06 21:29 UTC, merged