Hw6
ocelot335/tinkBot pull request #6
Opened 2024-03-24 19:10 UTC by ocelot335

Опять таки писал про курсач. Увы сейчас, не могу сделать, чуть позже доделаю

2024-03-31 19:40 UTC, ocelot335 commented
Извини, сейчас не успеваю сейчас сделать hw7. Его и hw6 я сдам на следующей неделе. Жаль, что чуть отстаю, сессия на неделе была((

2024-04-11 05:51 UTC, ocelot335 commented
Здесь hw6, hw7 и тесты для jooq. Извини, я ещё не понял, что мне сделать в 5 бонусной, у меня там 10/15.

2024-04-12 20:23 UTC, ocelot335 commented
Здесь сделано hw8

2024-04-13 12:31 UTC, lwbeamer commented
> я ещё не понял, что мне сделать в 5 бонусной, у меня там 10/15.

Кажется там только тестов не хватало

> Здесь hw6, hw7 и тесты для jooq

переводи на проверку на edu если готово, посмотрю (и ссылку на тот PR, в котором это сделано, как я понимаю в этом)

2024-04-16 09:36 UTC, lwbeamer requested changes
ОК, но не нашел тестов на новый функционал с кафкой. Как именно делать - на твое усмотрение, это может помочь - https://www.baeldung.com/spring-boot-kafka-testing

2024-04-16 09:36 UTC, lwbeamer commented on bot/src/main/java/edu/java/bot/configuration/KafkaConsumerConfiguration.java
> +    //Где вообще правильно создавать топики? Здесь? И здесь и у продюсера? В compose файле? В сторонних сервисах?
Чаще всего их создают руками не из кода (cli или сторонние сервисы), чтобы потом уже все сервисы понимали (разрабы перед написанием кода в доке условной смотрят) в какой топик им писать и из какого читать и что может оттуда прилететь. Для последнего используют Schema Registry - хранилище форматов сообщений грубо говоря, что то типа контракта между сервисами, которые общаются по кафке. В рамках этого проекта можно создавать из кода, где именно (продюсер или консьюмер) не важно. Иногда всё пишут вообще в одном классе а-ля KafkaConfiguration не разделяя

2024-05-05 22:51 UTC, merged